config/routes.rb
Rails.application.routes.draw do

  scope module: :public do

    #会員用
   devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
   }

    root :to => 'homes#top'
    get 'about' => 'homes#about'

    resources :customers, only: [:edit, :update, :show] do
     get 'unsubscribe'
     patch 'withdraw'
     member do
      get :favorites
    end
   end

   resources :profiles do
     resource :favorites, only: [:create, :destroy]
     resources :profile_comments, only: [:create, :destroy]
   end

   resources :posts
   get "search_post" => "posts#search_post"
   resources :chats, only: [:create, :show, :destroy]
   resources :notifications, only: [:index, :destroy, :update]
   resources :rooms, only: [:index]
   resources :events

  end


  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root :to => "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :profiles, only: [:index, :show, :update]
    resources :posts, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :profile_comments, dependent: :destroy
  has_many :customer_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_one :event, dependent: :destroy
  has_many :rooms, through: :customer_rooms

  #通知を送った
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy
  #通知を送られた
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_customer, only: [:show, :edit, :update]

  def index
    @q = Customer.ransack(params[:q])
    @customers = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    @profile = Profile.find_by(params[:id])
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to admin_customers_path(@customer.id)
    else
      @customers = Customer.page(params[:page])
      render :show
    end
  end

  def find_customer
    @customer = Customer.find(params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :profile_image, :is_deleted)
  end

end

app/controllers/customers_controller.rb
class Public::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
    @rooms = current_customer.customer_rooms.pluck(:room_id)
    @events = Event.all.where(customer_id: current_customer.id)
    @event = Event.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer)
    else
      render :edit
    end
  end

  def index
  end

  def unsubscribe
    @customer = Customer.find(params[:id])
  end

  def withdraw
    @customer = Customer.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def favorites
    @customer = Customer.find(params[:id])
    favorites = Favorite.where(customer_id: @customer.id).pluck(:profile_id)
    @favorite_profiles = Profile.find(favorites)
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :profile_image)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_search.html.erb
<%= search_form_for q, url: admin_customers_path do |f| %>
  <%= f.search_field :name_cont, placeholder: "名前" %>
  <%= f.submit "検索", class: "btn-sm btn-primary" %>
  <%= link_to 'クリア', request.path, class: "btn-sm btn-secondary" %>
<% end %>

app/views/admin/customers/index.html.erb
<h3 class="text-center my-3">会員一覧</h3>
<div class="container">
  <div class="d-flex justify-content-end mb-1">
     <%= render "search", q: @q %>
  </div>
  <div class="row justify-content-center">
    <div class="table-responsive">
      <table class="table table-hover text-nowrap">
        <thead class="thead-dark">
          <tr class="align-middle">
            <th>会員ID</th>
            <th>名前</th>
            <th>email</th>
            <th>プロフィール詳細</th>
            <th>会員</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <%= link_to customer.name, admin_customer_path(customer) %>
            </td>
            <td>
              <%= customer.email %>
            </td>
            <td>
              <% if customer.profile %>
               <%= link_to "詳細", admin_profile_path(customer.profile) %>
              <% else %>
               作成されていません
              <% end %>
            </td>
            <td>
              <% if customer.is_deleted == false %>
               <p class="text-success">有効</p>
              <% else %>
               <p class="text-danger">退会</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @customer %>
      <h2 class="text-center mt-3"><%= @customer.name %>さんの会員情報</h2>
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control email" %>
      </div>
      <div class="d-flex justify-content-center">
       <div class="col-10 btn-group mt-3" data-toggle="buttons">
        <label class="btn btn-outline-secondary active" style="width:50%">
          <%= f.radio_button :is_deleted, 'false' %> 有効
        </label>
        <label class="btn btn-outline-secondary" style="width:50%">
          <%= f.radio_button :is_deleted, 'true' %> 退会
        </label>
       </div>
      </div>

      <div class="form-group">
        <div class="d-flex justify-content-between mt-3">
          <%= link_to "戻る", admin_customers_path, class: "btn btn-secondary" %>
          <%= f.submit "変更を保存", class: 'btn btn-secondary' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>