config/routes.rb
Rails.application.routes.draw do

  scope module: :public do

    #会員用
   devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
   }

    root :to => 'homes#top'
    get 'about' => 'homes#about'

    resources :customers, only: [:edit, :update, :show] do
     get 'unsubscribe'
     patch 'withdraw'
     member do
      get :favorites
    end
   end

   resources :profiles do
     resource :favorites, only: [:create, :destroy]
     resources :profile_comments, only: [:create, :destroy]
   end

   resources :posts
   get "search_post" => "posts#search_post"
   resources :chats, only: [:create, :show, :destroy]
   resources :notifications, only: [:index, :destroy, :update]
   resources :rooms, only: [:index]
   resources :events

  end


  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root :to => "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :profiles, only: [:index, :show, :update]
    resources :posts, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer

  validates :game_on, presence: true
  validates :ground, presence: true
  validates :content, presence: true
  validates :category, presence: true

  def self.search(search_word)
    Post.where(['category LIKE?', "%#{search_word}%"])
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:game_on, :ground, :content, :category, :is_active)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_search.html.erb
<%= search_form_for q, url: admin_posts_path do |f| %>
  <%= f.search_field :customer_name_cont, placeholder: "名前" %>
  <%= f.search_field :category_cont, placeholder: "競技名" %>
  <%= f.submit "検索", class: "btn-sm btn-primary" %>
  <%= link_to 'クリア', request.path, class: "btn-sm btn-secondary" %>
<% end %>

app/views/admin/posts/index.html.erb
<h3 class="text-center my-3">募集一覧</h3>
<div class="container">
  <div class="d-flex justify-content-end mb-1">
    <%= render "search", q: @q %>
  </div>
  <div class="row justify-content-center">
    <div class="table-responsive">
      <table class="table table-hover text-nowrap">
        <thead class="thead-dark">
          <tr class="align-middle text-center">
            <th>会員ID</th>
            <th>名前</th>
            <th>試合日時</th>
            <th>競技名</th>
            <th>コメント</th>
            <th>募集状況</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td>
              <%= post.customer.id %>
            </td>
            <td>
              <% if post.customer.is_deleted == false %>
                <%= post.customer.name %>
              <% else %>
                <p class="text-danger">
                <%= post.customer.name %>
                </p>
              <% end %>
            </td>
            <td>
              <%= post.game_on %>
            </td>
            <td>
              <%= post.category %>
            </td>
            <td>
             <%= post.content.truncate(10) %>
            </td>
            <td>
              <% if post.is_active == true %>
               <%= link_to "募集中", admin_post_path(post) %>
              <% else %>
               <%= link_to "終了", admin_post_path(post) %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 mx-auto">
      <table class="table table-borderless">
        <h3 class="my-3">
          <%= render 'layouts/judgment', obj: @post %>
        </h3>
        <tbody>
          <tr>
            <td>チーム名</td>
            <td><%= @post.customer.name %></td>
          </tr>
          <tr>
            <td>競技名</td>
            <td><%= @post.category %></td>
          </tr>
          <tr>
            <td>試合日時</td>
            <td><%= @post.game_on %></td>
          </tr>
          <tr>
            <td>グラウンド</td>
            <td><%= @post.ground %></td>
          </tr>
          <tr>
            <td>コメント</td>
            <td width="250"><%= @post.content %></td>
          </tr>
          <tr>
            <td>募集状況</td>
            <td>
              <% if @post.is_active == true %>
              募集中
              <% else %>
              終了
              <% end %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to "戻る", admin_posts_path, class: "btn btn-secondary" %>
            </td>
            <td>
              <%= link_to "削除", admin_post_path(@post), method: :delete, class: "btn btn-danger" %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>