config/routes.rb
Rails.application.routes.draw do

  scope module: :public do

    #会員用
   devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
   }

    root :to => 'homes#top'
    get 'about' => 'homes#about'

    resources :customers, only: [:edit, :update, :show] do
     get 'unsubscribe'
     patch 'withdraw'
     member do
      get :favorites
    end
   end

   resources :profiles do
     resource :favorites, only: [:create, :destroy]
     resources :profile_comments, only: [:create, :destroy]
   end

   resources :posts
   get "search_post" => "posts#search_post"
   resources :chats, only: [:create, :show, :destroy]
   resources :notifications, only: [:index, :destroy, :update]
   resources :rooms, only: [:index]
   resources :events

  end


  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root :to => "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :profiles, only: [:index, :show, :update]
    resources :posts, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :customer
  belongs_to :room
  has_many :notifications, dependent: :destroy

  validates :message, presence: true

  def create_notification_by(current_customer)
    notification = current_customer.active_notifications.new(
      chat_id: id,
      room_id: room.id,
      visited_id: customer_id,
      visiter_id: current_customer.id,
      action: 'dm',
      checked: false
      )

      notification.save if notification.valid?
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :profile_comments, dependent: :destroy
  has_many :customer_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_one :event, dependent: :destroy
  has_many :rooms, through: :customer_rooms

  #通知を送った
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy
  #通知を送られた
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, presence: true

end

app/models/customer_room.rb
class CustomerRoom < ApplicationRecord

  belongs_to :customer
  belongs_to :room

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :customer

  validates :content, presence: true
  validates :title, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :profile
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :room, optional: true
  belongs_to :message, optional: true
  #通知を送った
  belongs_to :visiter, class_name: 'Customer', foreign_key: 'visiter_id'
  #通知を送られた
  belongs_to :visited, class_name: 'Customer', foreign_key: 'visited_id'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer

  validates :game_on, presence: true
  validates :ground, presence: true
  validates :content, presence: true
  validates :category, presence: true

  def self.search(search_word)
    Post.where(['category LIKE?', "%#{search_word}%"])
  end
end

app/models/profile.rb
class Profile < ApplicationRecord

  has_one_attached :profile_image
  belongs_to :customer
  has_many :favorites, dependent: :destroy
  has_many :profile_comments, dependent: :destroy

  validates :category, presence: true
  validates :address, presence: true
  validates :member, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :level, presence: true
  validates :activity_day, presence: true

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


  #既にいいねしているか確認
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
end

app/models/profile_comment.rb
class ProfileComment < ApplicationRecord
  belongs_to :customer
  belongs_to :profile

  validates :comment, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :chats
  has_many :customer_rooms
  has_many :customers, through: :customer_rooms
  has_many :notifications, dependent: :destroy


  def create_notification_dm!(current_customer, room_id, chat_id)
    #current_customer.id以外のcustomer_idを取得
    dm_customer = CustomerRoom.where(room_id: room_id).where.not(customer_id: current_customer.id).first.customer_id
    save_notification_dm!(current_customer, chat_id, dm_customer, room_id)
  end

  def save_notification_dm!(current_customer, chat_id, visited_id, room_id)
    notification = current_customer.active_notifications.new(
      room_id: room_id,
      chat_id: chat_id,
      visited_id: visited_id,
      action: 'dm',
      checked: false
    )
    notification.save! if notification.valid?
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @customers = Customer.where(is_deleted: false)
    @customer= @customers.page(params[:page]).per(5).order(created_at: :desc)
    @posts = Post.all
    @post = @posts.page(params[:page]).per(5).order(created_at: :desc)
    @profiles = Profile.all
    @profile = @profiles.page(params[:page]).per(5).order(created_at: :desc)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class Public::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
    @rooms = current_customer.customer_rooms.pluck(:room_id)
    @events = Event.all.where(customer_id: current_customer.id)
    @event = Event.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer)
    else
      render :edit
    end
  end

  def index
  end

  def unsubscribe
    @customer = Customer.find(params[:id])
  end

  def withdraw
    @customer = Customer.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def favorites
    @customer = Customer.find(params[:id])
    favorites = Favorite.where(customer_id: @customer.id).pluck(:profile_id)
    @favorite_profiles = Profile.find(favorites)
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :profile_image)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<nav class="navbar bg-dark navbar-expand-lg navbar-dark">
  <%= link_to "Entry!", admin_root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
  </button>
  <% if admin_signed_in? %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "会員一覧", admin_customers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "募集一覧", admin_posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "プロフィール一覧", admin_profiles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
  <% end %>
</nav>

app/views/layouts/_customer_header.html.erb
<nav class="navbar bg-dark navbar-expand-lg navbar-dark">
  <%= link_to "Entry!", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "チーム一覧", profiles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "募集一覧", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "投稿", new_post_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "マイページ", customer_path(current_customer), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件のエラー") %> </h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class='container mt-5 fixed-bottom'>
    <div class='mx-auto'>
      <p class ="text-white">© Entry!</p>
    	</div>
  </div>
</footer>

app/views/layouts/_guest_header.html.erb
<nav class="navbar bg-dark navbar-expand-lg navbar-dark">
  <%= link_to "Entry!", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ログイン", new_customer_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "チーム一覧", profiles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "募集一覧", posts_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_judgment.html.erb
<% if obj.customer.is_deleted == false %>
  <%= obj.customer.name %>
<% else %>
  <p class="text-danger">
  <%= obj.customer.name %>は退会しました
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entry!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#ecf0f1">
    <% if current_customer == nil && current_admin == nil %>
      <%= render 'layouts/guest_header' %>
    <% elsif current_customer == nil && current_admin.present? %>
      <%= render 'layouts/admin_header' %>
    <% else current_customer == true && current_admin == nill %>
      <%= render 'layouts/customer_header' %>
    <% end %>
    <main>
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </main>
     <%= render 'layouts/footer'%>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading mb-3 mt-3">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class:"mr-3" %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class:"ml-3" %>
  </div>
  <table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th class="text-center"><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>